version: '3.8'

services:
  backend:
    build:
      context: ./WebApplication1
    ports:
      - "5042:5042"
    volumes:
      - ./WebApplication1/pdfs:/app/pdfs
    environment:
      - ASPNETCORE_URLS=http://+:5042
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
